# _config.yml for Vrdondeti.github.io using Minimal Mistakes theme

# Site Settings
title: "Vema Dondeti | Data Science Portfolio"
name: "Vema Dondeti"
description: "A growing portfolio of data science projects focusing on AI, ML, NLP, and real-world analytics"
url: "https://vrdondeti.github.io"
baseurl: "" # the subpath of your site, leave empty for user.github.io style
repository: "Vrdondeti/Vrdondeti.github.io"
locale: "en-US"
theme: "minimal-mistakes-jekyll"

# Author Profile
author:
  name: "Vema Dondeti"
  avatar: "/assets/images/profile.png" # Add this image
  bio: "Aspiring Data Scientist | Generative AI Explorer | Python Enthusiast"
  location: "Texas, USA"
  email: "vemadondeti@gmail.com"  
  github: "Vrdondeti"
  
# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

# Navigation Links
# These links show in the top nav bar
navigation:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /portfolio/
  - title: "Contact"
    url: /contact/

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comments: false
      read_time: true

# Markdown settings
markdown: kramdown
highlighter: rouge

# Output
permalink: /:categories/:title/
timezone: America/Chicago

# SEO and Social
#twitter:
#  username: "vrdondeti"
#social:
#  name: "Vrdondeti"
#  links:
#    - "https://github.com/Vrdondeti"
#    - "https://linkedin.com/in/yourlinkedin"